"""
Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
nums = []
fibo = []

f1 = 1
f2 = 2

fibo.append(f1)
fibo.append(f2)

while True:
    f1, f2 = f2, f1 + f2
    if f2 < 4000000:
        fibo.append(f2)
    else:
        break

for n in fibo:
    if n % 2 == 0:
        nums.append(n)

print('Result =', sum(nums))