"""
Problem 12: Highly divisible triangular number

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be
1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
import time
from math import sqrt

start = time.time()

triangle_nums = []
summary = 0
i = 1
count = 0
while True:
    if count > 500:
        break
    digit = summary + i
    summary = digit
    i += 1
    triangle_nums.append(digit)
    count = 2
    for j in range(2, int(sqrt(digit)) + 1):
        if count > 500:
            print('Result =', digit)
            break
        if digit % j == 0:
            count += 2


print(triangle_nums)

end = time.time()
print('Time of execution = ' + str(end - start))
